---

os: osx
sudo: false

cache:
  directories:
    - .bundle/gems

language: ruby

rvm:
  - 2.2.9
  - 2.3.5
  - 2.4.3
  - 2.5.0
  - ruby-head

env:
  global: "NOCOV=true"

  matrix:
    - "LIBEDIT=true"
    - "LIBEDIT=false"

before_install:
  - brew update;
  - brew install shellcheck clang-format@3.8;
  - ln -s /usr/local/opt/clang-format@3.8/bin/clang-format /usr/local/bin/clang-format;
  - if [ "$LIBEDIT" == "true" ]; then
      brew install libedit;
    fi

install:
  - if [ "$LIBEDIT" == "true" ]; then
      rvm reinstall "$TRAVIS_RUBY_VERSION" --configure --enable-libedit;
    fi
  - gem update --system
  - gem update --remote bundler

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - script/ci.sh

matrix:
  fast_finish: true

  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change
